name: smudgeplot
channels:
  - conda-forge
  - bioconda
dependencies:
  - brotli=1.1.0=h00291cd_2
  - brotli-bin=1.1.0=h00291cd_2
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2025.1.31=h8857fd0_0
  - contourpy=1.3.1=py313ha0b1807_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.56.0=py313h717bdf5_0
  - freetype=2.12.1=h60636b9_2
  - kiwisolver=1.4.7=py313h0c4e38b_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=30_h7f60823_openblas
  - libbrotlicommon=1.1.0=h00291cd_2
  - libbrotlidec=1.1.0=h00291cd_2
  - libbrotlienc=1.1.0=h00291cd_2
  - libcblas=3.9.0=30_hff6cab4_openblas
  - libcxx=19.1.7=hf95d169_0
  - libdeflate=1.23=he65b83e_0
  - libexpat=2.6.4=h240833e_0
  - libffi=3.4.6=h281671d_0
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=30_h236ab99_openblas
  - liblzma=5.6.4=hd471939_0
  - libmpdec=4.0.0=hfdf4475_0
  - libopenblas=0.3.29=openmp_hbf64a52_0
  - libpng=1.6.47=h3c4a55f_0
  - libsqlite=3.49.1=hdb6dae5_1
  - libtiff=4.7.0=hb77a491_3
  - libwebp-base=1.5.0=h6cf52b4_0
  - libxcb=1.17.0=hf1f96e2_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.7=ha54dae1_0
  - matplotlib=3.10.0=py313habf4b1d_0
  - matplotlib-base=3.10.0=py313he981572_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h0622a9a_3
  - numpy=2.2.3=py313hc518a0f_0
  - openjpeg=2.5.3=h7fd6d84_0
  - openssl=3.4.1=hc426f3f_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py313h38cdd20_1
  - pillow=11.1.0=py313h0c4f865_0
  - pip=25.0.1=pyh145f28c_0
  - pthread-stubs=0.4=h00291cd_1002
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - python=3.13.2=h534c281_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.13=5_cp313
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h9e318b2_1
  - six=1.17.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tornado=6.4.2=py313h63b0ddb_0
  - tzdata=2025a=h78e105d_0
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - zstd=1.5.6=h915ae27_0
